>yi蓑烟雨任平生


## let

### 基本用法

ES6中新增了`let`命令，用来声明变量。它的用法类似于`var`，但是所声明的变量只在`let`命令所在的代码块内有效

```js
{
	let a = 0;
	var b = 1;
}
console.log(a)	//Uncaught ReferenceError: a is not defined
console.log(b) 	//1
```

上面在代码块中分别使用`let`与`var`声明了变量，然后我们在代码块之外访问两个变量，`let`声明的报错，而`var`声明的则可以访问。

`for`循环的计数器就很适合`let`命令

```js
for(let i = 0; i < 10; i ++) {
	//...
}
console.log(i)	//Uncaught ReferenceError: a is not defined
```

上面代码中，计数器`i`只在`for`循环中有效，而在循环体外访问就会报错

而看下面的代码

```js
var a = [];
for(var i = 0; i < 10; i ++) {
	a[i] = function() {
		console.log(i);
	}
}
a[6]();	//10
```
上面代码中，变量`i`是`var`命令声明的，在全局范围内都有效，所以全局只有一个变量`i`。每一次循环，变量`i`的值都会发生改变，而循环内被赋给数组`a`的函数内部的console.log(i)，里面的`i`指向的就是全局的`i`。也就是说，所有数组`a`的成员里面的`i`，指向的都是同一个`i`，导致运行时输出的是最后一轮的`i`的值，也就是10。

但如果我们使用`let`声明`i`的话，就会得到我们想要的结果了

```js
var a = [];
for(let i = 0; i < 10; i ++) {
	a[i] = function() {
		console.log(i);
	}
}
a[6]();	//6
```
由于`i`是由`let`声明的，所以当前的`i`只在本轮循环内有效，其实每一次循环的`i`都是一个新的变量。

另外，`for`循环有一个特别之处，设置循环变量的那部分是一个父作用域，而循环体内部是一个单独的子作用域

```js
for(let i = 0; i < 3; i ++) {
	let i = 'abc';
	console.log(i);		//abc abc abc
}
```
说明`for`循环中的`i`与内部变量`i`不在同一个作用域，但是这时候要注意，内部读取不到`for`循环中的`i`的值了


### 不存在变量提升

`var`因为有预编译的存在，会有变量提升的功能，在没赋值之前就可以访问，值为`undefined`。`let`跟`var`不一样，它声明的变量只能在赋值之后访问，否则报错

```js
console.log(a) //undefined
var a = 2;

console.log(b)	//Uncaught ReferenceError: b is not defined
let b = 1;
```


### 暂时性死区

只要块级作用域内存在`let`命令，它声明的变量就绑定这个区域，不再受外部影响。这也解释了上面的`for`循环中声明`i`，循环体内部再声明`i`的话就读取不到`for`循环中的`i`了。

```js
var a = 10;
if(true) {
	a = 20;	//Uncaught ReferenceError: a is not defined
	let a;
}
```
上面代码中，存在全局变量`a`，但是块级作用域内`let`又声明了一个局部变量`a`，导致后者绑定这个块级作用域，所以在`let`声明变量前，对`a`赋值会报错。

ES6明确规定，如果区块中存在`let`和`const`命令，这个区块对这些命令声明的变量，从一开始就形成了封闭作用域。凡是在声明之前就使用这些变量，就会报错。

总之，在代码块内，使用`let`命令声明变量之前，该变量都是不可用的。这在语法上，称为“暂时性死区”（temporal dead zone，简称 TDZ）。

```js
if(true){
	//TDZ开始
	a = 10;	//Uncaught ReferenceError: a is not defined
	console.log(a); //Uncaught ReferenceError: a is not defined
	let a;
	//TDZ结束
	console.log(a);	//undefined
	a = 10;
	console.log(a); //10
}
```
上面代码中，在`let`声明之前，都属于`a`变量的死区。

在死区内会发生哪些奇奇怪怪的东西呢

```js
console.log(typeof a);
let a;
```
大家猜，会输出什么呢 `Uncaught ReferenceError: a is not defined`。看到没，连`typeof`都是不安全的操作了，作为比较的话如果一个变量压根就没被声明，使用`typeof`反而不会报错

```js
console.log(typeof a) //undefined
```

还有很多比较隐蔽的暂时性死区。总之，暂时性死区的本质就是，只要一进入当前作用域，所要获取的变量就已经存在了，但是不可取，只有等到声明变量的那一行出现，才可以获取和使用该变量。


### 不允许重新声明

`let`不允许在同一个作用域内，重复声明同一个变量

```js
function fn() {
	let a = 10;
	var a = 11;	//Uncaught SyntaxError: Identifier 'a' has already been declared
}
function fn() {
	let a = 10;
	let a = 'abc';	//Uncaught SyntaxError: Identifier 'a' has already been declared
}
```
因此函数内部的形参不能再次声明
 
```js
function fn(a,b) {
	let a = a;	//Uncaught SyntaxError: Identifier 'a' has already been declared
	let b = b;	//Uncaught SyntaxError: Identifier 'a' has already been declared
	{
		let a;	//不会报错
	}
}
```



## 块级作用域

我们都知道在ES5中只有全局全局作用域和函数作用域，并没有块级作用域，没有块级作用域会导致什么呢。

第一种，内层变量覆盖掉外层变量

```js
var tmp = 10;
function fn() {
	console.log(tmp);	//undefined
	if(false) {
		var tmp = 20;
	}
}
fn();
```

可以看到，当函数执行的时候，输出的是undefined，这是为什么呢，因为作用域链和预编译的缘故，当执行`console.log(tmp)`的时候，他会从作用域链对象的最顶层开始往下查找，访问当前函数的执行期上下文对象，但是因为预编译变量提升的缘故，所以这个时候访问`tmp`是`undefined`

第二种，用来计数的循环变量泄漏为全局变量

```js
var str = 'abcd';
for(var i = 0; i < str.length; i ++) {
	console.log(str[i]);	//a b c d
}
console.log(i);	//5
```

当函数执行完毕之后，用来控制循环的变量`i`仍未消失，泄漏成了全局变量。

### ES6块级作用域

在ES6中`let`实际上就为了JavaScript提供了块级作用域，只要有`{}`，其内部就是一个单独的作用域

```js
function fn() {
	let a = 10;
	console.log(a);		//10
	if(true){
		let a = 20;
	}
	console.log(a);		//10
}
fn();
```

上面的函数中存在两个代码块，都声明了变量`a`，但是最后输出均是10。这表明外层代码块并不受内层代码块的影响。如果两次都使用`let`声明对象，最终的结果会是10，20。

ES6允许块级作用域的任意嵌套。

```js
{
	{
		{
			{
				{
					let a = 10;
				}
			}
		}
	}
}
```
上面代码使用了一个五层的块级作用域，外层作用域无法访问内层作用域

```js
{
	{
		{
			{
				{
					let a = 10;
				}
				console.log(a); //Uncaught ReferenceError: a is not defined
			}
		}
	}
}
```

内层作用域可以声明一个跟外层作用域同名的变量
```js
{
	{
		{
			{
				let a = 20;
				{
					let a = 10;
					console.log(a);	//10
				}
				console.log(a); //20;
			}
		}
	}
}
```

块级作用域的出现，完全顶替了立即执行函数
```js
//立即执行函数
(function() {
	var a = 10;
	...
}())

//块级作用域
{
	let a = 10;
}
```

### 块级作用域与函数声明

ES5规定，函数只能在全局作用域和函数作用域内声明，不能在块级作用域内声明。

```js
//情形一
if(true) {
	function f() {}
}

//情形二
try{
	function f() {}
}catch(e) {
	...
}
```
上面的两种情形在ES5中都是违法的。

但是浏览器为了兼容之前的旧代码，还是支持在块级作用域之内声明函数，因此上面的代码都能运行，并不会报错。

ES6引入了块级作用域，明确允许在块级作用域中声明函数。ES6规定，块级作用域中，函数声明语句类似于`let`，块级作用域之外不可引用

```js
function fn() {
	console.log("I'm outside!");
}
(function() {
	if(false) {
		function fn() {
			console.log("I'm inside");
		}
	}
	fn();	// I'm outside
}())
```
上面的代码在ES5中运行会得到`I'm inside`,因为在`if`内声明的函数`f`因为预编译的存在会被提升到函数顶部，实际运行的代码如下

```js
function fn() {
	console.log("I'm outside!");
}
(function() {
	function fn() {
		console.log("I'm inside");
	}
	if(false) {
		
	}
	fn();	// I'm outside
}())
```

ES6就完全不一样了，理论上会得到`I'm outside`。因为块级作用域内声明的函数类似于`let`，对作用域之外没有影响。但是如果真的在ES6浏览器中运行上面的代码，是会报错的。

```js
function fn() {
	console.log("I'm outside!");
}
(function() {
	console.log(fn);	//undefined
	if(false) {
		function fn() {
			console.log("I'm inside");
		}
	}
	fn();	//Uncaught TypeError: fn is not a function
}())
```

为什么呢？

原来，如果改变了块级作用域内声明的函数的处理规则，显然会对老代码产生很大影响。为了减轻因此产生的不兼容问题，ES6在[附录B](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-block-level-function-declarations-web-legacy-compatibility-semantics)里面规定，浏览器的实现可以不遵守上面的规定，有自己的[行为方式](https://stackoverflow.com/questions/31419897/what-are-the-precise-semantics-of-block-level-functions-in-es6)。

	- 允许在块级作用域内声明函数。
	- 函数声明类似于var，即会提升到全局作用域或函数作用域的头部。
	- 同时，函数声明还会提升到所在的块级作用域的头部。

注意，上面三条规则只对 ES6 的浏览器实现有效，其他环境的实现不用遵守，还是将块级作用域的函数声明当作`let`处理。

根据这三条规则，在浏览器的 ES6 环境中，块级作用域内声明的函数，行为类似于`var`声明的变量。

那么在符合ES6的浏览器中，上面的代码实际上是运行下面的代码

```js
//符合ES6的浏览器
function fn() {
	console.log("I'm outside!");
}
(function() {
	var fn = undefined;
	console.log(fn);	//undefined
	if(false) {
		function fn() {
			console.log("I'm inside");
		}
	}
	fn();	//Uncaught TypeError: fn is not a function
}())
```

因此考虑到环境导致的行为差异太大，应该避免在块级作用域内声明函数。如果确实需要，也应该写成函数表达式，而不是函数声明语句。

```js
//函数声明语句
{
	let a = 10;
	function f() {
		return a;
	}
}

//函数表达式
{
	let a = 10;
	let f = function() {
		return a;
	}
}
```

另外还有一个需要注意的点是，ES6块级作用域允许声明函数的规则，只在使用大括号的情况下成立，如果没有使用大括号就会报错。

```js
//不报错
'use strict';
if(true) {
	function f() {};
}
//报错
'use strict';
if(true)
	function f() {};
```


## const 

### 基本用法

`const`声明一个只读的变量，被声明的常量的值不能改变。

```js
const PI = 3.1415926;
console.log(PI); //3.1415926
PI = 3.14;	//Uncaught TypeError: Assignment to constant variable
```
上面代码表明`const`声明的变量改变其值会报错。

`const`声明的变量不能改变值,那就意味着在我声明变量的时候必须赋值，不能留到以后再给其赋值,否则会报错

```js
const PI;
console.log(PI);	//Uncaught SyntaxError: Missing initializer in const declaration
```

其他的与`let`一致，只在块级作用域内有效，变量不提升存在暂时性死区，不可重复声明。


### 本质

`const`声明的变量不可改变其值的根本原因不是变量的值不能改变，而是变量指向的内存地址不能改变。对于简单的数据类型（number, string, boolean),值就保存在变量指向的内存地址。但是对于复合型数据（Array, Object),变量指向的内存地址，保存的只是一个指针，`const`只能保证我一直指向这个内存地址，意思这个指针是固定的，但是我不管这个指针指向的数据结构会不会改变。

```js
const stu = {};
stu.name = 'tongteng';
stu.sex = 'male';
console.log(stu);	//{name: 'tongteng', sex: 'male'}
stu = {		//Uncaught TypeError: Assignment to constant variable
	name: 'suijinlei',
	sex: 'mail'
}
```
从上面的代码可以看出，`stu`保存的只是一个地址，我们可以改变这个地址指向的数据，但是如果我们重新给`stu`赋予一个新地址是不可以的。

类似的还有数组
```js
const arr = [];	
arr.push(1);	//[1]
console.log(arr);
arr = [2];	//Uncaught TypeError: Assignment to constant variable
```
`str`保存的是一个数组的地址，我们可以对该数组进行操作，但是如果重新给`str`赋予一个新数组的地址时不可取的

如果真的想将一个对象冻结，不能修改对象的话使用`Object.freeze`方法。

```js
const stu = Object.freeze({});
//如果我们这个时候给对象添加属性
stu.name = 'tongteng';
//常规模式下上面这个添加属性语句不起作用
console.log(stu);	//{}
//严格模式下会报错
//Uncaught TypeError: Cannot add property name, object is not extensible
```

但是如果对象里面的某个`key`的`value`也为对象

```js
const stu = Object.freeze({
	name: {}
});
stu.name.sex = 'male';
console.log(stu);	//{name: {sex: male}}
```
是可以改变的，所以我们可以写一个函数来一个深层冻结，类似于对象的深层拷贝

```js
var constantize = (obj) => {
	Object.freeze(obj);
	Object.keys(obj).forEach( (key, i) => {
		if( typeof obj[key] === 'object' ) {
			constantize(obj[key]);
		}
	})
}
let obj = {
	name: {
		sex: 'male'
	}
}
constantize(obj);
```
此时一个对象obj才算一个真正的冻结对象。





>既然选择了远方，便只顾风雨兼程。

—— HandSomeTT 2017.11.04


